<script>
const textDomain =	{
	ok: 		'<?php echo _s( 'Ok', 'nexo' );?>',
	cancel: 	'<?php echo _s( 'Annuler', 'nexo' );?>',
	orderDetails: 	'<?php echo _s( 'Détails de la commande', 'nexo' );?>',
	loading: 	'<?php echo _s( 'Chargement...', 'nexo' );?>',
	orderOptions: '<?php echo _s( 'Options Avancées', 'nexo' );?>',
	orderComplete: '<?php echo _s( 'Paiement Intégrale', 'nexo' );?>',
	orderPartial: '<?php echo _s( 'Paiement Partiel', 'nexo' );?>',
	orderUnpaid: '<?php echo _s( 'Impayée', 'nexo' );?>',
	statusRequired: '<?php echo _s( 'Vous devez choisir un état avant de continuer', 'nexo' );?>',
	print: '<?php echo _s( 'Imprimer le reçu', 'nexo' );?>',
	notSet: 	'<?php echo _s( 'Non Spécifié', 'nexo' );?>',
	name: '<?php echo _s( 'Nom', 'nexo' );?>',
	surname: '<?php echo _s( 'Prénom', 'nexo' );?>',
	email: '<?php echo _s( 'Email', 'nexo' );?>',
	address_1: '<?php echo _s( 'Address 1', 'nexo' );?>',
	address_2: '<?php echo _s( 'Address 2', 'nexo' );?>',
	phone: '<?php echo _s( 'Téléphone', 'nexo' );?>',
	country: '<?php echo _s( 'Pays', 'nexo' );?>',
	state: '<?php echo _s( 'Etat', 'nexo' );?>',
	cantProceed: '<?php echo _s( 'Impossible de continuer', 'nexo' );?>',
	city: '<?php echo _s( 'Ville', 'nexo' );?>',
	enterprise: '<?php echo _s( 'Entreprise', 'nexo' );?>',
	pobox: '<?php echo _s( 'Boite Postale', 'nexo' );?>',
	confirm: '<?php echo _s( 'Souhaitez-vous confirmer ?', 'nexo' );?>',
	shipped: '<?php echo _s( 'Expédié', 'nexo' );?>',
	pending: '<?php echo _s( 'En attente', 'nexo' );?>',
	processing: '<?php echo _s( 'En cours', 'nexo' );?>',
	delivered: '<?php echo _s( 'Livrée', 'nexo' );?>',
	error: '<?php echo _s( 'Erreur', 'nexo' );?>',
	undefined: '<?php echo _s( 'Non défini', 'nexo' );?>',
	unknow: 	'<?php echo _s( 'Inconnu', 'nexo' );?>',
	incoming: '<?php echo _s( 'Paiement', 'nexo' );?>',
	withstock: '<?php echo _s( 'Avec retour de stock', 'nexo' );?>',
	stockless: '<?php echo _s( 'Sans retour de stock', 'nexo' );?>',
	failedToInitializePrinters: '<?php echo _s( 'Erreur durant l\'initilisation des imprimantes.', 'nexo' );?>',
	successfullyInitializedPrinters: '<?php echo _s( 'Imprimantes initialisée correctement', 'nexo' );?>',
	notEnoughStock: '<?php echo _s( 'Stock insuffisant !', 'nexo' );?>',
	defective: '<?php echo _s( 'Défectueux', 'nexo' );?>',
	inGoodCondition: '<?php echo _s( 'En bon état', 'nexo' );?>',
	outcoming: '<?php echo _s( 'Remboursement', 'nexo' );?>',
	mustSelectProductStatus: '<?php echo _s( 'Vous devez sélectionner l\'état du produit !', 'nexo' );?>',
	mustSelectProduct: '<?php echo _s( 'Vous devez sélectionner un produit !', 'nexo' );?>',
	orderPartiallyRefunded: '<?php echo _s( 'Partiellement Remboursée', 'nexo' );?>',
	orderRefunded: '<?php echo _s( 'Entièrement remboursée', 'nexo' );?>',
	refundCartEmpty: '<?php echo _s( 'Vous ne pouvez pas procéder si vous n\'avez ajouté aucun produit à rembourser.', 'nexo' );?>',
	refundRequireValidAmount: '<?php echo _s( 'Pour effectuer un remboursement, vous devez spécifier une valeur manuelle valide', 'nexo' );?>',
	confirmPartialRefund: '<?php echo _s( 'Un remboursement manuel sera effectué. Veuillez donner une explication à ce remboursement.', 'nexo' );?>',
	confirmRefund: '<?php echo _s( 'Un remboursement intégral sera effectué. Veuillez donner une explication à ce remboursement.', 'nexo' );?>',
	cantExceedTotal: '<?php echo _s( 'Le remboursement ne peut pas être supérieure à la valeur totale de la commande', 'nexo' );?>',
	completed: '<?php echo _s( 'Terminée', 'nexo' );?>',
	paymentSuccess: '<?php echo _s( 'Le paiement a été correctement effectuée', 'nexo' );?>',
	proceedToPayment: '<?php echo _s( 'Souhaitez-vous effectuer le paiement ? Une nouvelle entrée sera ajoutée à la liste des paiements de cette commande. Cette action est irreversible.','nexo' );?>',
	requirePaymentGateway: '<?php echo _s( 'Vous devez choisir un moyen de paiement & fournir un montant supérieur à 0 avant de continuer.', 'nexo' );?>'
}
</script>